version: '3'
services:

  app:
    container_name: app
    restart: always
    build:
      context: ./
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://db:3306/db_proposta
      DB_USERNAME: admin
      DB_PASSWORD: admin
      ANALISE_URL: http://analise:9999/api/solicitacao
      CONTA_URL: http://contas:8888/api/cartoes



  db:
    image: mysql:8.0.26
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: proposta
      MYSQL_DATABASE: db_proposta
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

